// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_gitea

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func GiteaProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type GiteaModel struct {
}
