// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_team

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func TeamDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"can_create_org_repo": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the team can create repositories in the organization",
				MarkdownDescription: "Whether the team can create repositories in the organization",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the team",
				MarkdownDescription: "The description of the team",
			},
			"id": schema.Int64Attribute{
				Required:            true,
				Description:         "id of the team to get",
				MarkdownDescription: "id of the team to get",
			},
			"includes_all_repositories": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the team has access to all repositories in the organization",
				MarkdownDescription: "Whether the team has access to all repositories in the organization",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the team",
				MarkdownDescription: "The name of the team",
			},
			"units": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"units_map": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
		},
	}
}

type TeamModel struct {
	CanCreateOrgRepo        types.Bool   `tfsdk:"can_create_org_repo"`
	Description             types.String `tfsdk:"description"`
	Id                      types.Int64  `tfsdk:"id"`
	IncludesAllRepositories types.Bool   `tfsdk:"includes_all_repositories"`
	Name                    types.String `tfsdk:"name"`
	Units                   types.List   `tfsdk:"units"`
	UnitsMap                types.Map    `tfsdk:"units_map"`
}
