// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_team

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func TeamDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"can_create_org_repo": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the team can create repositories in the organization",
				MarkdownDescription: "Whether the team can create repositories in the organization",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the team",
				MarkdownDescription: "The description of the team",
			},
			"id": schema.Int64Attribute{
				Required:            true,
				Description:         "id of the team to get",
				MarkdownDescription: "id of the team to get",
			},
			"includes_all_repositories": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the team has access to all repositories in the organization",
				MarkdownDescription: "Whether the team has access to all repositories in the organization",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the team",
				MarkdownDescription: "The name of the team",
			},
			"organization": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"avatar_url": schema.StringAttribute{
						Computed:            true,
						Description:         "The URL of the organization's avatar",
						MarkdownDescription: "The URL of the organization's avatar",
					},
					"description": schema.StringAttribute{
						Computed:            true,
						Description:         "The description of the organization",
						MarkdownDescription: "The description of the organization",
					},
					"email": schema.StringAttribute{
						Computed:            true,
						Description:         "The email address of the organization",
						MarkdownDescription: "The email address of the organization",
					},
					"full_name": schema.StringAttribute{
						Computed:            true,
						Description:         "The full display name of the organization",
						MarkdownDescription: "The full display name of the organization",
					},
					"id": schema.Int64Attribute{
						Computed:            true,
						Description:         "The unique identifier of the organization",
						MarkdownDescription: "The unique identifier of the organization",
					},
					"location": schema.StringAttribute{
						Computed:            true,
						Description:         "The location of the organization",
						MarkdownDescription: "The location of the organization",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "The name of the organization",
						MarkdownDescription: "The name of the organization",
					},
					"repo_admin_change_team_access": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether repository administrators can change team access",
						MarkdownDescription: "Whether repository administrators can change team access",
					},
					"username": schema.StringAttribute{
						Computed:            true,
						Description:         "username of the organization\ndeprecated",
						MarkdownDescription: "username of the organization\ndeprecated",
					},
					"visibility": schema.StringAttribute{
						Computed:            true,
						Description:         "The visibility level of the organization (public, limited, private)",
						MarkdownDescription: "The visibility level of the organization (public, limited, private)",
					},
					"website": schema.StringAttribute{
						Computed:            true,
						Description:         "The website URL of the organization",
						MarkdownDescription: "The website URL of the organization",
					},
				},
				CustomType: OrganizationType{
					ObjectType: types.ObjectType{
						AttrTypes: OrganizationValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Organization represents an organization",
				MarkdownDescription: "Organization represents an organization",
			},
			"units": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"units_map": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
		},
	}
}

type TeamModel struct {
	CanCreateOrgRepo        types.Bool        `tfsdk:"can_create_org_repo"`
	Description             types.String      `tfsdk:"description"`
	Id                      types.Int64       `tfsdk:"id"`
	IncludesAllRepositories types.Bool        `tfsdk:"includes_all_repositories"`
	Name                    types.String      `tfsdk:"name"`
	Organization            OrganizationValue `tfsdk:"organization"`
	Units                   types.List        `tfsdk:"units"`
	UnitsMap                types.Map         `tfsdk:"units_map"`
}

var _ basetypes.ObjectTypable = OrganizationType{}

type OrganizationType struct {
	basetypes.ObjectType
}

func (t OrganizationType) Equal(o attr.Type) bool {
	other, ok := o.(OrganizationType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OrganizationType) String() string {
	return "OrganizationType"
}

func (t OrganizationType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	avatarUrlAttribute, ok := attributes["avatar_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`avatar_url is missing from object`)

		return nil, diags
	}

	avatarUrlVal, ok := avatarUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`avatar_url expected to be basetypes.StringValue, was: %T`, avatarUrlAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	fullNameAttribute, ok := attributes["full_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`full_name is missing from object`)

		return nil, diags
	}

	fullNameVal, ok := fullNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`full_name expected to be basetypes.StringValue, was: %T`, fullNameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	locationAttribute, ok := attributes["location"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`location is missing from object`)

		return nil, diags
	}

	locationVal, ok := locationAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`location expected to be basetypes.StringValue, was: %T`, locationAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	repoAdminChangeTeamAccessAttribute, ok := attributes["repo_admin_change_team_access"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`repo_admin_change_team_access is missing from object`)

		return nil, diags
	}

	repoAdminChangeTeamAccessVal, ok := repoAdminChangeTeamAccessAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`repo_admin_change_team_access expected to be basetypes.BoolValue, was: %T`, repoAdminChangeTeamAccessAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	visibilityAttribute, ok := attributes["visibility"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`visibility is missing from object`)

		return nil, diags
	}

	visibilityVal, ok := visibilityAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`visibility expected to be basetypes.StringValue, was: %T`, visibilityAttribute))
	}

	websiteAttribute, ok := attributes["website"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`website is missing from object`)

		return nil, diags
	}

	websiteVal, ok := websiteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`website expected to be basetypes.StringValue, was: %T`, websiteAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OrganizationValue{
		AvatarUrl:                 avatarUrlVal,
		Description:               descriptionVal,
		Email:                     emailVal,
		FullName:                  fullNameVal,
		Id:                        idVal,
		Location:                  locationVal,
		Name:                      nameVal,
		RepoAdminChangeTeamAccess: repoAdminChangeTeamAccessVal,
		Username:                  usernameVal,
		Visibility:                visibilityVal,
		Website:                   websiteVal,
		state:                     attr.ValueStateKnown,
	}, diags
}

func NewOrganizationValueNull() OrganizationValue {
	return OrganizationValue{
		state: attr.ValueStateNull,
	}
}

func NewOrganizationValueUnknown() OrganizationValue {
	return OrganizationValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOrganizationValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OrganizationValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OrganizationValue Attribute Value",
				"While creating a OrganizationValue value, a missing attribute value was detected. "+
					"A OrganizationValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OrganizationValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OrganizationValue Attribute Type",
				"While creating a OrganizationValue value, an invalid attribute value was detected. "+
					"A OrganizationValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OrganizationValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OrganizationValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OrganizationValue Attribute Value",
				"While creating a OrganizationValue value, an extra attribute value was detected. "+
					"A OrganizationValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OrganizationValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOrganizationValueUnknown(), diags
	}

	avatarUrlAttribute, ok := attributes["avatar_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`avatar_url is missing from object`)

		return NewOrganizationValueUnknown(), diags
	}

	avatarUrlVal, ok := avatarUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`avatar_url expected to be basetypes.StringValue, was: %T`, avatarUrlAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewOrganizationValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewOrganizationValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	fullNameAttribute, ok := attributes["full_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`full_name is missing from object`)

		return NewOrganizationValueUnknown(), diags
	}

	fullNameVal, ok := fullNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`full_name expected to be basetypes.StringValue, was: %T`, fullNameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewOrganizationValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	locationAttribute, ok := attributes["location"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`location is missing from object`)

		return NewOrganizationValueUnknown(), diags
	}

	locationVal, ok := locationAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`location expected to be basetypes.StringValue, was: %T`, locationAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewOrganizationValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	repoAdminChangeTeamAccessAttribute, ok := attributes["repo_admin_change_team_access"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`repo_admin_change_team_access is missing from object`)

		return NewOrganizationValueUnknown(), diags
	}

	repoAdminChangeTeamAccessVal, ok := repoAdminChangeTeamAccessAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`repo_admin_change_team_access expected to be basetypes.BoolValue, was: %T`, repoAdminChangeTeamAccessAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewOrganizationValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	visibilityAttribute, ok := attributes["visibility"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`visibility is missing from object`)

		return NewOrganizationValueUnknown(), diags
	}

	visibilityVal, ok := visibilityAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`visibility expected to be basetypes.StringValue, was: %T`, visibilityAttribute))
	}

	websiteAttribute, ok := attributes["website"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`website is missing from object`)

		return NewOrganizationValueUnknown(), diags
	}

	websiteVal, ok := websiteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`website expected to be basetypes.StringValue, was: %T`, websiteAttribute))
	}

	if diags.HasError() {
		return NewOrganizationValueUnknown(), diags
	}

	return OrganizationValue{
		AvatarUrl:                 avatarUrlVal,
		Description:               descriptionVal,
		Email:                     emailVal,
		FullName:                  fullNameVal,
		Id:                        idVal,
		Location:                  locationVal,
		Name:                      nameVal,
		RepoAdminChangeTeamAccess: repoAdminChangeTeamAccessVal,
		Username:                  usernameVal,
		Visibility:                visibilityVal,
		Website:                   websiteVal,
		state:                     attr.ValueStateKnown,
	}, diags
}

func NewOrganizationValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OrganizationValue {
	object, diags := NewOrganizationValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOrganizationValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OrganizationType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOrganizationValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOrganizationValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOrganizationValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOrganizationValueMust(OrganizationValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OrganizationType) ValueType(ctx context.Context) attr.Value {
	return OrganizationValue{}
}

var _ basetypes.ObjectValuable = OrganizationValue{}

type OrganizationValue struct {
	AvatarUrl                 basetypes.StringValue `tfsdk:"avatar_url"`
	Description               basetypes.StringValue `tfsdk:"description"`
	Email                     basetypes.StringValue `tfsdk:"email"`
	FullName                  basetypes.StringValue `tfsdk:"full_name"`
	Id                        basetypes.Int64Value  `tfsdk:"id"`
	Location                  basetypes.StringValue `tfsdk:"location"`
	Name                      basetypes.StringValue `tfsdk:"name"`
	RepoAdminChangeTeamAccess basetypes.BoolValue   `tfsdk:"repo_admin_change_team_access"`
	Username                  basetypes.StringValue `tfsdk:"username"`
	Visibility                basetypes.StringValue `tfsdk:"visibility"`
	Website                   basetypes.StringValue `tfsdk:"website"`
	state                     attr.ValueState
}

func (v OrganizationValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 11)

	var val tftypes.Value
	var err error

	attrTypes["avatar_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["full_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["location"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["repo_admin_change_team_access"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["visibility"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["website"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 11)

		val, err = v.AvatarUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["avatar_url"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.FullName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["full_name"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Location.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["location"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.RepoAdminChangeTeamAccess.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["repo_admin_change_team_access"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		val, err = v.Visibility.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["visibility"] = val

		val, err = v.Website.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["website"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OrganizationValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OrganizationValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OrganizationValue) String() string {
	return "OrganizationValue"
}

func (v OrganizationValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"avatar_url":                    basetypes.StringType{},
		"description":                   basetypes.StringType{},
		"email":                         basetypes.StringType{},
		"full_name":                     basetypes.StringType{},
		"id":                            basetypes.Int64Type{},
		"location":                      basetypes.StringType{},
		"name":                          basetypes.StringType{},
		"repo_admin_change_team_access": basetypes.BoolType{},
		"username":                      basetypes.StringType{},
		"visibility":                    basetypes.StringType{},
		"website":                       basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"avatar_url":                    v.AvatarUrl,
			"description":                   v.Description,
			"email":                         v.Email,
			"full_name":                     v.FullName,
			"id":                            v.Id,
			"location":                      v.Location,
			"name":                          v.Name,
			"repo_admin_change_team_access": v.RepoAdminChangeTeamAccess,
			"username":                      v.Username,
			"visibility":                    v.Visibility,
			"website":                       v.Website,
		})

	return objVal, diags
}

func (v OrganizationValue) Equal(o attr.Value) bool {
	other, ok := o.(OrganizationValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AvatarUrl.Equal(other.AvatarUrl) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.FullName.Equal(other.FullName) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Location.Equal(other.Location) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.RepoAdminChangeTeamAccess.Equal(other.RepoAdminChangeTeamAccess) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	if !v.Visibility.Equal(other.Visibility) {
		return false
	}

	if !v.Website.Equal(other.Website) {
		return false
	}

	return true
}

func (v OrganizationValue) Type(ctx context.Context) attr.Type {
	return OrganizationType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OrganizationValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"avatar_url":                    basetypes.StringType{},
		"description":                   basetypes.StringType{},
		"email":                         basetypes.StringType{},
		"full_name":                     basetypes.StringType{},
		"id":                            basetypes.Int64Type{},
		"location":                      basetypes.StringType{},
		"name":                          basetypes.StringType{},
		"repo_admin_change_team_access": basetypes.BoolType{},
		"username":                      basetypes.StringType{},
		"visibility":                    basetypes.StringType{},
		"website":                       basetypes.StringType{},
	}
}
