// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_branch_protection

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BranchProtectionResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"approvals_whitelist_teams": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"approvals_whitelist_username": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"block_admin_merge_override": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"block_on_official_review_requests": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"block_on_outdated_branch": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"block_on_rejected_reviews": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"branch_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Deprecated: true",
				MarkdownDescription: "Deprecated: true",
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"dismiss_stale_approvals": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"enable_approvals_whitelist": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"enable_force_push": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"enable_force_push_allowlist": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"enable_merge_whitelist": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"enable_push": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"enable_push_whitelist": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"enable_status_check": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"force_push_allowlist_deploy_keys": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"force_push_allowlist_teams": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"force_push_allowlist_usernames": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"ignore_stale_approvals": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"merge_whitelist_teams": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"merge_whitelist_usernames": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "name of protected branch",
				MarkdownDescription: "name of protected branch",
			},
			"owner": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "owner of the repo",
				MarkdownDescription: "owner of the repo",
			},
			"priority": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Priority is the priority of this branch protection rule",
				MarkdownDescription: "Priority is the priority of this branch protection rule",
			},
			"protected_file_patterns": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"push_whitelist_deploy_keys": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"push_whitelist_teams": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"push_whitelist_usernames": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"repo": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "name of the repo",
				MarkdownDescription: "name of the repo",
			},
			"require_signed_commits": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"required_approvals": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"rule_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "RuleName is the name of the branch protection rule",
				MarkdownDescription: "RuleName is the name of the branch protection rule",
			},
			"status_check_contexts": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"unprotected_file_patterns": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type BranchProtectionModel struct {
	ApprovalsWhitelistTeams       types.List   `tfsdk:"approvals_whitelist_teams"`
	ApprovalsWhitelistUsername    types.List   `tfsdk:"approvals_whitelist_username"`
	BlockAdminMergeOverride       types.Bool   `tfsdk:"block_admin_merge_override"`
	BlockOnOfficialReviewRequests types.Bool   `tfsdk:"block_on_official_review_requests"`
	BlockOnOutdatedBranch         types.Bool   `tfsdk:"block_on_outdated_branch"`
	BlockOnRejectedReviews        types.Bool   `tfsdk:"block_on_rejected_reviews"`
	BranchName                    types.String `tfsdk:"branch_name"`
	CreatedAt                     types.String `tfsdk:"created_at"`
	DismissStaleApprovals         types.Bool   `tfsdk:"dismiss_stale_approvals"`
	EnableApprovalsWhitelist      types.Bool   `tfsdk:"enable_approvals_whitelist"`
	EnableForcePush               types.Bool   `tfsdk:"enable_force_push"`
	EnableForcePushAllowlist      types.Bool   `tfsdk:"enable_force_push_allowlist"`
	EnableMergeWhitelist          types.Bool   `tfsdk:"enable_merge_whitelist"`
	EnablePush                    types.Bool   `tfsdk:"enable_push"`
	EnablePushWhitelist           types.Bool   `tfsdk:"enable_push_whitelist"`
	EnableStatusCheck             types.Bool   `tfsdk:"enable_status_check"`
	ForcePushAllowlistDeployKeys  types.Bool   `tfsdk:"force_push_allowlist_deploy_keys"`
	ForcePushAllowlistTeams       types.List   `tfsdk:"force_push_allowlist_teams"`
	ForcePushAllowlistUsernames   types.List   `tfsdk:"force_push_allowlist_usernames"`
	IgnoreStaleApprovals          types.Bool   `tfsdk:"ignore_stale_approvals"`
	MergeWhitelistTeams           types.List   `tfsdk:"merge_whitelist_teams"`
	MergeWhitelistUsernames       types.List   `tfsdk:"merge_whitelist_usernames"`
	Name                          types.String `tfsdk:"name"`
	Owner                         types.String `tfsdk:"owner"`
	Priority                      types.Int64  `tfsdk:"priority"`
	ProtectedFilePatterns         types.String `tfsdk:"protected_file_patterns"`
	PushWhitelistDeployKeys       types.Bool   `tfsdk:"push_whitelist_deploy_keys"`
	PushWhitelistTeams            types.List   `tfsdk:"push_whitelist_teams"`
	PushWhitelistUsernames        types.List   `tfsdk:"push_whitelist_usernames"`
	Repo                          types.String `tfsdk:"repo"`
	RequireSignedCommits          types.Bool   `tfsdk:"require_signed_commits"`
	RequiredApprovals             types.Int64  `tfsdk:"required_approvals"`
	RuleName                      types.String `tfsdk:"rule_name"`
	StatusCheckContexts           types.List   `tfsdk:"status_check_contexts"`
	UnprotectedFilePatterns       types.String `tfsdk:"unprotected_file_patterns"`
	UpdatedAt                     types.String `tfsdk:"updated_at"`
}
