// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_org

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OrgResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"avatar_url": schema.StringAttribute{
				Computed:            true,
				Description:         "The URL of the organization's avatar",
				MarkdownDescription: "The URL of the organization's avatar",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The description of the organization",
				MarkdownDescription: "The description of the organization",
			},
			"email": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The email address of the organization",
				MarkdownDescription: "The email address of the organization",
			},
			"full_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The full display name of the organization",
				MarkdownDescription: "The full display name of the organization",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The unique identifier of the organization",
				MarkdownDescription: "The unique identifier of the organization",
			},
			"location": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The location of the organization",
				MarkdownDescription: "The location of the organization",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the organization",
				MarkdownDescription: "The name of the organization",
			},
			"org": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "name of the organization to get",
				MarkdownDescription: "name of the organization to get",
			},
			"repo_admin_change_team_access": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether repository administrators can change team access",
				MarkdownDescription: "Whether repository administrators can change team access",
			},
			"username": schema.StringAttribute{
				Required:            true,
				Description:         "username of the organization",
				MarkdownDescription: "username of the organization",
			},
			"visibility": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "possible values are `public` (default), `limited` or `private`",
				MarkdownDescription: "possible values are `public` (default), `limited` or `private`",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"public",
						"limited",
						"private",
					),
				},
			},
			"website": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The website URL of the organization",
				MarkdownDescription: "The website URL of the organization",
			},
		},
	}
}

type OrgModel struct {
	AvatarUrl                 types.String `tfsdk:"avatar_url"`
	Description               types.String `tfsdk:"description"`
	Email                     types.String `tfsdk:"email"`
	FullName                  types.String `tfsdk:"full_name"`
	Id                        types.Int64  `tfsdk:"id"`
	Location                  types.String `tfsdk:"location"`
	Name                      types.String `tfsdk:"name"`
	Org                       types.String `tfsdk:"org"`
	RepoAdminChangeTeamAccess types.Bool   `tfsdk:"repo_admin_change_team_access"`
	Username                  types.String `tfsdk:"username"`
	Visibility                types.String `tfsdk:"visibility"`
	Website                   types.String `tfsdk:"website"`
}
